<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DICE_Library" nsURI="http://es.unizar.disco.dice/libraries/DICE_Library/1.0"
    nsPrefix="DICE_Library">
  <eSubpackages name="Complex_DICE_Types" nsURI="http://es.unizar.disco.dice/libraries/Complex_DICE_Types/1.0"
      nsPrefix="Complex_DICE_Types">
    <eSubpackages name="Complex_Data_Types" nsURI="http://es.unizar.disco.dice/libraries/Complex_Data_Types/1.0"
        nsPrefix="Complex_Data_Types">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="Data_Types"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EClass" name="DiceDataVolume">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_DataSize"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DiceDataSpecification">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_DataSize"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="refModel" ordered="false"
            eType="#//Basic_DICE_Types/Basic_Enumeration_Types/RefType"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="refDataFormat" ordered="false"
            eType="#//Basic_DICE_Types/Basic_Enumeration_Types/RefDataFormatType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DiceChannelSpecification">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="rate" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Frequency"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_DataSize"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="Basic_DICE_Types" nsURI="http://es.unizar.disco.dice/libraries/Basic_DICE_Types/1.0"
      nsPrefix="Basic_DICE_Types">
    <eSubpackages name="Basic_Data_Types" nsURI="http://es.unizar.disco.dice/libraries/Basic_Data_Types/1.0"
        nsPrefix="Basic_Data_Types">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="Data_Types"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EClass" name="NFP_Privacy">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="expr" ordered="false"
            lowerBound="1" eType="ecore:EDataType ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//MARTE_DataTypes/VSL_Expression"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" ordered="false"
            lowerBound="1" eType="ecore:EEnum ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/SourceKind"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ScriptType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="scriptId" ordered="false"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="scriptUri" ordered="false"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="scriptKind" ordered="false"
            lowerBound="1" eType="#//Basic_DICE_Types/Basic_Enumeration_Types/LifeCycleElementType"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="Basic_Enumeration_Types" nsURI="http://es.unizar.disco.dice/libraries/Basic_Enumeration_Types/1.0"
        nsPrefix="Basic_Enumeration_Types">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="Enumeration_Types"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EEnum" name="RefType">
        <eLiterals name="cassandra"/>
        <eLiterals name="hdfs" value="1"/>
        <eLiterals name="mongodb" value="2"/>
        <eLiterals name="mysql" value="3"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="RefDataFormatType">
        <eLiterals name="json"/>
        <eLiterals name="plain" value="1"/>
        <eLiterals name="xml" value="2"/>
        <eLiterals name="avro" value="3"/>
        <eLiterals name="parquet" value="4"/>
        <eLiterals name="yaml" value="5"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="LifeCycleElementType">
        <eLiterals name="start"/>
        <eLiterals name="stop" value="1"/>
        <eLiterals name="install" value="2"/>
        <eLiterals name="create" value="3"/>
        <eLiterals name="download" value="4"/>
        <eLiterals name="preconfigured" value="5"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="TechType">
        <eLiterals name="hadoop"/>
        <eLiterals name="spark" value="1"/>
        <eLiterals name="storm" value="2"/>
        <eLiterals name="oryx2" value="3"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="ProcessingType">
        <eLiterals name="stream"/>
        <eLiterals name="batch" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="SourceType">
        <eLiterals name="dataStream"/>
        <eLiterals name="webapi" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="ConstraintType">
        <eLiterals name="less"/>
        <eLiterals name="lessEqual" value="1"/>
        <eLiterals name="equal" value="2"/>
        <eLiterals name="greaterEqual" value="3"/>
        <eLiterals name="greater" value="4"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="WorkflowOperation">
        <eLiterals name="groupBy"/>
        <eLiterals name="sum" value="1"/>
        <eLiterals name="count" value="2"/>
        <eLiterals name="split" value="3"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="MapType">
        <eLiterals name="regexMapper"/>
        <eLiterals name="fieldSelectionMapper" value="1"/>
        <eLiterals name="chainMapper" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="ReduceType">
        <eLiterals name="fieldSelectionReducer"/>
        <eLiterals name="chainReducer" value="1"/>
        <eLiterals name="intSumReducer" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="StreamPolicy">
        <eLiterals name="all"/>
        <eLiterals name="shuffle" value="1"/>
        <eLiterals name="field" value="2"/>
        <eLiterals name="global" value="3"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="Scheduling">
        <eLiterals name="capacity"/>
        <eLiterals name="fifo" value="1"/>
        <eLiterals name="fair" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="VMSize">
        <eLiterals name="Small"/>
        <eLiterals name="Medium" value="1"/>
        <eLiterals name="Large" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="ProviderType">
        <eLiterals name="fco"/>
        <eLiterals name="openstack" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="DDSMcomponentType">
        <eLiterals name="MasterSlavePlatform"/>
        <eLiterals name="PeerToPeerPlatform" value="1"/>
        <eLiterals name="PeerNode" value="2"/>
        <eLiterals name="PeersQuorum" value="3"/>
        <eLiterals name="CassandraSeed" value="4"/>
        <eLiterals name="MasterNode" value="5"/>
        <eLiterals name="SlaveNode" value="6"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="ComputationType">
        <eLiterals name="distributed"/>
        <eLiterals name="parallel" value="1"/>
        <eLiterals name="distributedParallel" value="2"/>
        <eLiterals name="microBench" value="3"/>
        <eLiterals name="sorting" value="4"/>
        <eLiterals name="grep" value="5"/>
        <eLiterals name="wordCount" value="6"/>
        <eLiterals name="collabFiltering" value="7"/>
        <eLiterals name="naiveBayes" value="8"/>
        <eLiterals name="bfs" value="9"/>
        <eLiterals name="pageRank" value="10"/>
        <eLiterals name="kMeans" value="11"/>
        <eLiterals name="connectedComponents" value="12"/>
        <eLiterals name="relQuery" value="13"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
