<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DICE" nsURI="http://es.unizar.disco.dice/profiles/DICE/1.0"
    nsPrefix="DICE">
  <eClassifiers xsi:type="ecore:EEnum" name="Dummy"/>
  <eSubpackages name="DICE_UML_Extensions" nsURI="http://es.unizar.disco.dice/profiles/DICE_UML_Extensions/1.0"
      nsPrefix="DICE_UML_Extensions">
    <eSubpackages name="DPIM" nsURI="http://es.unizar.disco.dice/profiles/DPIM/1.0"
        nsPrefix="DPIM">
      <eClassifiers xsi:type="ecore:EClass" name="DpimComputationNode" eSuperTypes="../../com.masdes.dam.static.profile/resources/DAM.ecore#//DAM_UML_Extensions/System/Core/DaComponent">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="nodeThroughput" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Frequency"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false"
            eType="ecore:EEnum DICE_Library.ecore#//Basic_DICE_Types/Basic_Enumeration_Types/ComputationType"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetTech" ordered="false"
            eType="ecore:EEnum DICE_Library.ecore#//Basic_DICE_Types/Basic_Enumeration_Types/TechType"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="procType" ordered="false"
            eType="ecore:EEnum DICE_Library.ecore#//Basic_DICE_Types/Basic_Enumeration_Types/ProcessingType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DpimFilterNode" eSuperTypes="#//DICE_UML_Extensions/DPIM/DpimComputationNode">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputRatio" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Frequency"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputRation" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Frequency"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DpimVisualizationNode" eSuperTypes="#//DICE_UML_Extensions/DPIM/DpimComputationNode"/>
      <eClassifiers xsi:type="ecore:EClass" name="DpimSourceNode" eSuperTypes="#//DICE_UML_Extensions/DPIM/DpimComputationNode">
        <eStructuralFeatures xsi:type="ecore:EReference" name="store" ordered="false"
            eType="ecore:EClass DICE_Library.ecore#//Complex_DICE_Types/Complex_Data_Types/DiceDataVolume"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="provides" ordered="false"
            eType="ecore:EClass DICE_Library.ecore#//Complex_DICE_Types/Complex_Data_Types/DiceDataSpecification"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceType" ordered="false"
            eType="ecore:EEnum DICE_Library.ecore#//Basic_DICE_Types/Basic_Enumeration_Types/SourceType"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="rate" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Frequency"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DpimStorageNode" eSuperTypes="../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_Foundations/GRM/StorageResource">
        <eStructuralFeatures xsi:type="ecore:EReference" name="respondsTo" ordered="false"
            eType="ecore:EClass DICE_Library.ecore#//Complex_DICE_Types/Complex_Data_Types/DiceDataSpecification"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="crudRate" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Frequency"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DpimChannel" eSuperTypes="../../com.masdes.dam.static.profile/resources/DAM.ecore#//DAM_UML_Extensions/System/Core/DaConnector">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="rate" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Frequency"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageBroker" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="channelDescription"
            ordered="false" eType="ecore:EClass DICE_Library.ecore#//Complex_DICE_Types/Complex_Data_Types/DiceChannelSpecification"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DpimScenario" eSuperTypes="../../com.masdes.dam.static.profile/resources/DAM.ecore#//DAM_UML_Extensions/System/Core/DaService"/>
    </eSubpackages>
    <eSubpackages name="DTSM" nsURI="http://es.unizar.disco.dice/profiles/DTSM/1.0"
        nsPrefix="DTSM">
      <eSubpackages name="Core" nsURI="http://es.unizar.disco.dice/profiles/DTSM/Core/1.0"
          nsPrefix="Core">
        <eClassifiers xsi:type="ecore:EClass" name="CoreComputationNode" abstract="true"
            eSuperTypes="#//DICE_UML_Extensions/DPIM/DpimComputationNode">
          <eStructuralFeatures xsi:type="ecore:EReference" name="hasSuccessor" ordered="false"
              upperBound="-1" eType="#//DICE_UML_Extensions/DTSM/Core/CoreComputationNode"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="processInputData"
              ordered="false" upperBound="-1" eType="#//DICE_UML_Extensions/DTSM/Core/CoreData"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="realise" ordered="false"
              lowerBound="1" eType="#//DICE_UML_Extensions/DTSM/Core/CoreDirectAcyclicGraph"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="produceOutputData"
              ordered="false" lowerBound="1" upperBound="-1" eType="#//DICE_UML_Extensions/DTSM/Core/CoreData"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="CoreData" abstract="true">
          <eStructuralFeatures xsi:type="ecore:EReference" name="location" ordered="false"
              lowerBound="1" upperBound="-1" eType="#//DICE_UML_Extensions/DTSM/Core/CoreDataSource"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="hasSpecification"
              ordered="false" lowerBound="1" eType="ecore:EClass DICE_Library.ecore#//Complex_DICE_Types/Complex_Data_Types/DiceDataSpecification"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="hasVolume" ordered="false"
              lowerBound="1" eType="ecore:EClass DICE_Library.ecore#//Complex_DICE_Types/Complex_Data_Types/DiceDataVolume"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
              lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="CoreDataSource" abstract="true"
            eSuperTypes="#//DICE_UML_Extensions/DPIM/DpimStorageNode"/>
        <eClassifiers xsi:type="ecore:EClass" name="CoreDirectAcyclicGraph" abstract="true"
            eSuperTypes="../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_AnalysisModel/GQAM/GaScenario">
          <eStructuralFeatures xsi:type="ecore:EReference" name="hasSourceNode" ordered="false"
              lowerBound="1" upperBound="-1" eType="#//DICE_UML_Extensions/DTSM/Core/CoreDAGSourceNode"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
              lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="CoreDAGSourceNode" abstract="true"
            eSuperTypes="#//DICE_UML_Extensions/DTSM/Core/CoreDAGNode">
          <eStructuralFeatures xsi:type="ecore:EReference" name="readFrom" ordered="false"
              lowerBound="1" upperBound="-1" eType="#//DICE_UML_Extensions/DTSM/Core/CoreDataSource"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="CoreDAGNode" abstract="true" eSuperTypes="../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_AnalysisModel/GQAM/GaStep #//DICE_UML_Extensions/DPIM/DpimSourceNode">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="parallelism" ordered="false"
              lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Integer"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" ordered="false"
              lowerBound="1" eType="ecore:EEnum DICE_Library.ecore#//Basic_DICE_Types/Basic_Enumeration_Types/WorkflowOperation"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="hasSuccessor" ordered="false"
              upperBound="-1" eType="#//DICE_UML_Extensions/DTSM/Core/CoreDAGNode"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="CoreStorageNode" abstract="true"
            eSuperTypes="#//DICE_UML_Extensions/DTSM/Core/CoreDataSource">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="database" ordered="false"
              lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" ordered="false"
              lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" ordered="false"
              lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        </eClassifiers>
      </eSubpackages>
      <eSubpackages name="Storm" nsURI="http://es.unizar.disco.dice/profiles/DTSM/Storm/1.0"
          nsPrefix="Storm">
        <eClassifiers xsi:type="ecore:EClass" name="StormBolt" eSuperTypes="#//DICE_UML_Extensions/DTSM/Core/CoreDAGNode">
          <eAnnotations source="duplicates">
            <eAnnotations source="failure">
              <details key="upperBound" value="1"/>
            </eAnnotations>
            <contents xsi:type="ecore:EReference" name="failure" ordered="false" upperBound="-1"
                eType="ecore:EClass ../../com.masdes.dam.static.profile/resources/DAM_Library.ecore#//Complex_DA_Types/Complex_Data_Types/DaFailure"
                containment="true">
              <eAnnotations source="redefines" references="../../com.masdes.dam.static.profile/resources/DAM.ecore#//DAM_UML_Extensions/System/Core/DaComponent/failure"/>
            </contents>
          </eAnnotations>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="d" ordered="false"
              eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="alpha" ordered="false"
              eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="sigma" ordered="false"
              eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="minRebootTime" ordered="false"
              eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxRebootTime" ordered="false"
              eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="StormSpout" eSuperTypes="#//DICE_UML_Extensions/DTSM/Core/CoreDAGSourceNode">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="avgEmitRate" ordered="false"
              eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="StormScenarioTopology" eSuperTypes="#//DICE_UML_Extensions/DTSM/Core/CoreDirectAcyclicGraph">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="queueThreshold" ordered="false"
              eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxTaskParallelism"
              ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxSpoutPending"
              ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReliable" ordered="false"
              eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="StormApplication" eSuperTypes="#//DICE_UML_Extensions/DTSM/Core/CoreComputationNode">
          <eStructuralFeatures xsi:type="ecore:EReference" name="hasMasterNode" ordered="false"
              eType="#//DICE_UML_Extensions/DTSM/Storm/StormNimbus"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="hasSlaveNode" ordered="false"
              eType="#//DICE_UML_Extensions/DTSM/Storm/StormSupervisor"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="dependsOnZookeeper"
              ordered="false" eType="#//DICE_UML_Extensions/DTSM/Storm/StormZookeeper"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="StormNimbus">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="taskTimeout" ordered="false"
              eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="supervisorTimeout"
              ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="monitorFrequency"
              ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Classifier"
              ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="StormSupervisor">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="monitroFrequency"
              ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="workerSatrtTimeout"
              ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="workerTimeout" ordered="false"
              eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="heartbrackFrequency"
              ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="memoryCapacity" ordered="false"
              eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpuCapacity" ordered="false"
              eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Classifier"
              ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="StormZookeeper">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="sessionTimeout" ordered="false"
              eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectionTimeout"
              ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="retryTime" ordered="false"
              eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="retryInterval" ordered="false"
              eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" ordered="false"
              eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" ordered="false"
              eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Classifier"
              ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="StormStreamStep" eSuperTypes="../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_AnalysisModel/GQAM/GaStep">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="numTuples" ordered="false"
              lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Integer"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="grouping" ordered="false"
              lowerBound="1" eType="ecore:EEnum DICE_Library.ecore#//Basic_DICE_Types/Basic_Enumeration_Types/StreamPolicy"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="probFields" ordered="false"
              upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        </eClassifiers>
      </eSubpackages>
      <eSubpackages name="Hadoop" nsURI="http://es.unizar.disco.dice/profiles/DTSM/Hadoop/1.0"
          nsPrefix="Hadoop">
        <eClassifiers xsi:type="ecore:EClass" name="HadoopMapReduceJob">
          <eStructuralFeatures xsi:type="ecore:EReference" name="mapResucePhases"
              ordered="false" lowerBound="1" upperBound="-1" eType="#//DICE_UML_Extensions/DTSM/Hadoop/HadoopMapReducePhase"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Classifier"
              ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="HadoopMapReducePhase">
          <eStructuralFeatures xsi:type="ecore:EReference" name="hasMap" ordered="false"
              lowerBound="1" eType="#//DICE_UML_Extensions/DTSM/Hadoop/HadoopMap"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="hasReduce" ordered="false"
              lowerBound="1" eType="#//DICE_UML_Extensions/DTSM/Hadoop/HadoopReduce"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="output" ordered="false"
              eType="#//DICE_UML_Extensions/DTSM/Core/CoreData"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Classifier"
              ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="HadoopMap" eSuperTypes="#//DICE_UML_Extensions/DTSM/Hadoop/HadoopOperation">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false"
              eType="ecore:EEnum DICE_Library.ecore#//Basic_DICE_Types/Basic_Enumeration_Types/MapType"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="HadoopOperation" eSuperTypes="../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_AnalysisModel/GQAM/GaStep">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="parallelism" ordered="false"
              eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Integer"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="nTasks" ordered="false"
              upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Integer"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="HadoopReduce" eSuperTypes="#//DICE_UML_Extensions/DTSM/Hadoop/HadoopOperation">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false"
              eType="ecore:EEnum DICE_Library.ecore#//Basic_DICE_Types/Basic_Enumeration_Types/ReduceType"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="HadoopScenario" eSuperTypes="../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_AnalysisModel/GQAM/GaScenario">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobSchedule" ordered="false"
              eType="ecore:EEnum DICE_Library.ecore#//Basic_DICE_Types/Basic_Enumeration_Types/Scheduling"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="HadoopWorkloadEvent" eSuperTypes="../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_AnalysisModel/GQAM/GaWorkloadEvent">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="hadoopPopulation"
              ordered="false" upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Integer"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="hadoopExtDelay" ordered="false"
              upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="HadoopComputationNode" eSuperTypes="#//DICE_UML_Extensions/DTSM/Core/CoreComputationNode">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="nCores" ordered="false"
              upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Integer"/>
        </eClassifiers>
      </eSubpackages>
    </eSubpackages>
    <eSubpackages name="DDSM" nsURI="http://es.unizar.disco.dice/profiles/DDSM/1.0"
        nsPrefix="DDSM">
      <eClassifiers xsi:type="ecore:EClass" name="DdsmExternalComponent" eSuperTypes="#//DICE_UML_Extensions/DDSM/DdsmComponent">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="provider" ordered="false"
            lowerBound="1" eType="ecore:EEnum DICE_Library.ecore#//Basic_DICE_Types/Basic_Enumeration_Types/ProviderType"
            defaultValueLiteral="fco"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceType" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="region" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="login" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Device" ordered="false"
            lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Device"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DdsmComponent" abstract="true" eSuperTypes="#//DICE_UML_Extensions/DDSM/DdsmCloudElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="providedPortsList"
            ordered="false" upperBound="-1" eType="#//DICE_UML_Extensions/DDSM/DdsmPort"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DdsmCloudElement" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertiesList" ordered="false"
            upperBound="-1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DdsmPort" eSuperTypes="#//DICE_UML_Extensions/DDSM/DdsmCloudElement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLocal" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"
            defaultValueLiteral="false"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="portNumber" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_CommunicationPath"
            ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//CommunicationPath"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DdsmInternalComponent" eSuperTypes="#//DICE_UML_Extensions/DDSM/DdsmComponent">
        <eStructuralFeatures xsi:type="ecore:EReference" name="requiredPort" ordered="false"
            upperBound="-1" eType="#//DICE_UML_Extensions/DDSM/DdsmPort"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFrontEnd" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
            defaultValueLiteral="false"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentType" ordered="false"
            eType="ecore:EEnum DICE_Library.ecore#//Basic_DICE_Types/Basic_Enumeration_Types/DDSMcomponentType"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Node" ordered="false"
            lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Node"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="protected" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"
            defaultValueLiteral="false"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="launch_script" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DdsmHeterogeneousCluster" eSuperTypes="#//DICE_UML_Extensions/DDSM/DdsmExternalComponent">
        <eStructuralFeatures xsi:type="ecore:EReference" name="hasVM" ordered="false"
            upperBound="-1" eType="#//DICE_UML_Extensions/DDSM/DdsmVMsCluster"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DdsmVMsCluster" eSuperTypes="#//DICE_UML_Extensions/DDSM/DdsmExternalComponent">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="is64os" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"
            defaultValueLiteral="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageId" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCores" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxRam" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxStorage" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
            defaultValueLiteral="0"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="minCores" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="minRam" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="minStorage" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
            defaultValueLiteral="0"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="os" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="securityGroup" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="privateKey" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="sshKey" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicAddress" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="instances" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
            defaultValueLiteral="1"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="genericSize" ordered="false"
            lowerBound="1" eType="ecore:EEnum DICE_Library.ecore#//Basic_DICE_Types/Basic_Enumeration_Types/VMSize"
            defaultValueLiteral="Small"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DdsmYarnCluster" eSuperTypes="#//DICE_UML_Extensions/DDSM/DdsmMasterSlavePlatform">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_ExecutionEnvironment"
            ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//ExecutionEnvironment"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DdsmMasterSlavePlatform" eSuperTypes="#//DICE_UML_Extensions/DDSM/DdsmInternalComponent">
        <eStructuralFeatures xsi:type="ecore:EReference" name="masterHost" ordered="false"
            eType="#//DICE_UML_Extensions/DDSM/DdsmVMsCluster"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DdsmZookeeperCluster" eSuperTypes="#//DICE_UML_Extensions/DDSM/DdsmPeerToPeerPlatform">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="tickTime" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
            defaultValueLiteral="1500"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="syncLimit" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
            defaultValueLiteral="10"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="initLimit" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
            defaultValueLiteral="5"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DdsmPeerToPeerPlatform" eSuperTypes="#//DICE_UML_Extensions/DDSM/DdsmInternalComponent"/>
      <eClassifiers xsi:type="ecore:EClass" name="DdsmKafkaCluster" eSuperTypes="#//DICE_UML_Extensions/DDSM/DdsmPeerToPeerPlatform">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_ExecutionEnvironment"
            ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//ExecutionEnvironment"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DdsmStormCluster" eSuperTypes="#//DICE_UML_Extensions/DDSM/DdsmMasterSlavePlatform">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="taskTimeout" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
            defaultValueLiteral="60"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="supervisorFrequency"
            ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
            defaultValueLiteral="60"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="queueSize" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
            defaultValueLiteral="10000"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="monitorFrequency" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
            defaultValueLiteral="40"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="retryTimes" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
            defaultValueLiteral="5"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="retryInterval" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
            defaultValueLiteral="2000"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="workerStartTimeout"
            ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpuCapacity" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="memoryCapacity" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="heartbeatFrequency"
            ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_ExecutionEnvironment"
            ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//ExecutionEnvironment"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DdsmJobSubmission">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Deployment" ordered="false"
            lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Deployment"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfSubmission"
            ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="intervalBetweenSubmission"
            ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DdsmBigDataJob">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="application" ordered="false"
            lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="application_class"
            ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Artifact" ordered="false"
            lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Artifact"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="application_name" ordered="false"
            lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="arguments" ordered="false"
            lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DdsmJobDeployedFrom">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Dependency" ordered="false"
            lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Dependency"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DdsmHdfsCluster" eSuperTypes="#//DICE_UML_Extensions/DDSM/DdsmMasterSlavePlatform"/>
      <eClassifiers xsi:type="ecore:EClass" name="DdsmCassandraCluster" eSuperTypes="#//DICE_UML_Extensions/DDSM/DdsmPeerToPeerPlatform">
        <eStructuralFeatures xsi:type="ecore:EReference" name="seedHost" ordered="false"
            eType="#//DICE_UML_Extensions/DDSM/DdsmVMsCluster"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="key_cache_keys_to_save"
            ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="key_cache_save_period"
            ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="memtable_cleanup_threshold"
            ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="memtable_flush_writers"
            ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="authenticator_enabled"
            ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="authorizer_enabled"
            ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="permission_validity_in_ms"
            ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
