<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DICE" nsURI="http://es.unizar.disco.dice/profiles/DICE/1.0"
    nsPrefix="DICE">
  <eClassifiers xsi:type="ecore:EEnum" name="dummy"/>
  <eSubpackages name="DICE_UML_Extensions" nsURI="http://es.unizar.disco.dice/profiles/DICE_UML_Extensions/1.0"
      nsPrefix="DICE_UML_Extensions">
    <eSubpackages name="DPIM" nsURI="http://es.unizar.disco.dice/profiles/DPIM/1.0"
        nsPrefix="DPIM">
      <eClassifiers xsi:type="ecore:EClass" name="DiceComponent" eSuperTypes="../../com.masdes.dam.static.profile/resources/DAM.ecore#//DAM_UML_Extensions/System/Core/DaComponent">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="throughput" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Frequency"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false"
            eType="ecore:EEnum DICE_Library.ecore#//Basic_DICE_Types/Basic_Enumeration_Types/ComputationType"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetTech" ordered="false"
            eType="ecore:EEnum DICE_Library.ecore#//Basic_DICE_Types/Basic_Enumeration_Types/TechType"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="procType" ordered="false"
            eType="ecore:EEnum DICE_Library.ecore#//Basic_DICE_Types/Basic_Enumeration_Types/ProcessingType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DiceFilterNode" eSuperTypes="#//DICE_UML_Extensions/DPIM/DiceComponent">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputRatio" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Frequency"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputRation" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Frequency"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DiceVisualizationNode" eSuperTypes="#//DICE_UML_Extensions/DPIM/DiceComponent"/>
      <eClassifiers xsi:type="ecore:EClass" name="DiceSourceNode" eSuperTypes="#//DICE_UML_Extensions/DPIM/DiceComponent">
        <eStructuralFeatures xsi:type="ecore:EReference" name="store" ordered="false"
            eType="ecore:EClass DICE_Library.ecore#//Complex_DICE_Types/Complex_Data_Types/DiceDataVolume"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="provides" ordered="false"
            eType="ecore:EClass DICE_Library.ecore#//Complex_DICE_Types/Complex_Data_Types/DiceDataSpecification"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceType" ordered="false"
            eType="ecore:EEnum DICE_Library.ecore#//Basic_DICE_Types/Basic_Enumeration_Types/SourceType"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="rate" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Frequency"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DiceStorageResource" eSuperTypes="../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_Foundations/GRM/StorageResource">
        <eStructuralFeatures xsi:type="ecore:EReference" name="respondsTo" ordered="false"
            eType="ecore:EClass DICE_Library.ecore#//Complex_DICE_Types/Complex_Data_Types/DiceDataSpecification"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="crudRate" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Frequency"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DiceChannel" eSuperTypes="../../com.masdes.dam.static.profile/resources/DAM.ecore#//DAM_UML_Extensions/System/Core/DaConnector">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="rate" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Frequency"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageBroker" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="channelDescription"
            ordered="false" eType="ecore:EClass DICE_Library.ecore#//Complex_DICE_Types/Complex_Data_Types/DiceChannelSpecification"
            containment="true"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
