<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DAM" nsURI="http://com.masdes.dam/profiles/DAM/1.0" nsPrefix="DAM">
  <eClassifiers xsi:type="ecore:EEnum" name="dummy"/>
  <eSubpackages name="DAM_UML_Extensions" nsURI="http://com.masdes.dam/profiles/DAM_UML_Extensions/1.0"
      nsPrefix="DAM_UML_Extensions">
    <eSubpackages name="System" nsURI="http://com.masdes.dam/profiles/System/1.0"
        nsPrefix="System">
      <eSubpackages name="Core" nsURI="http://com.masdes.dam/profiles/Core/1.0" nsPrefix="Core">
        <eClassifiers xsi:type="ecore:EClass" name="DaComponent" eSuperTypes="../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_Foundations/GRM/Resource">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateful" ordered="false"
              eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="origin" ordered="false"
              eType="ecore:EEnum DAM_Library.ecore#//Basic_DA_Types/Basic_Enumeration_Types/Origin"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="failureCoverage"
              ordered="false" upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Percentage"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="percPermFault" ordered="false"
              upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Percentage"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssAvail" ordered="false"
              upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Percentage"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="unreliability" ordered="false"
              upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_CommonType"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="reliability" ordered="false"
              upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_CommonType"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="missionTime" ordered="false"
              upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_CommonType"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="availLevel" ordered="false"
              upperBound="-1" eType="ecore:EDataType DAM_Library.ecore#//Basic_DA_Types/Basic_Data_Types/DaLevel"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="reliabilityLevel"
              ordered="false" upperBound="-1" eType="ecore:EDataType DAM_Library.ecore#//Basic_DA_Types/Basic_Data_Types/DaLevel"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="safetyLevel" ordered="false"
              upperBound="-1" eType="ecore:EDataType DAM_Library.ecore#//Basic_DA_Types/Basic_Data_Types/DaLevel"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="complexity" ordered="false"
              upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="fault" ordered="false"
              upperBound="-1" eType="ecore:EClass DAM_Library.ecore#//Complex_DA_Types/Complex_Data_Types/DaFault"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="error" ordered="false"
              upperBound="-1" eType="ecore:EClass DAM_Library.ecore#//Complex_DA_Types/Complex_Data_Types/DaError"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="failure" ordered="false"
              upperBound="-1" eType="ecore:EClass DAM_Library.ecore#//Complex_DA_Types/Complex_Data_Types/DaFailure"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="hazard" ordered="false"
              upperBound="-1" eType="ecore:EClass DAM_Library.ecore#//Complex_DA_Types/Complex_Data_Types/DaHazard"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="repair" ordered="false"
              upperBound="-1" eType="ecore:EClass DAM_Library.ecore#//Complex_DA_Types/Complex_Data_Types/DaRepair"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="substitutedBy" ordered="false"
              upperBound="-1" eType="#//DAM_UML_Extensions/System/Redundancy/DaSpare"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="DaService" eSuperTypes="../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_AnalysisModel/GQAM/GaScenario">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="execProb" ordered="false"
              upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssAvail" ordered="false"
              upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Percentage"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="instAvail" ordered="false"
              upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_CommonType"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="unreliability" ordered="false"
              upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_CommonType"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="reliability" ordered="false"
              upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_CommonType"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="missionTime" ordered="false"
              upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_CommonType"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="availLevel" ordered="false"
              upperBound="-1" eType="ecore:EDataType DAM_Library.ecore#//Basic_DA_Types/Basic_Data_Types/DaLevel"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="reliabLevel" ordered="false"
              upperBound="-1" eType="ecore:EDataType DAM_Library.ecore#//Basic_DA_Types/Basic_Data_Types/DaLevel"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="safetyLevel" ordered="false"
              upperBound="-1" eType="ecore:EDataType DAM_Library.ecore#//Basic_DA_Types/Basic_Data_Types/DaLevel"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="complexity" ordered="false"
              upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="failure" ordered="false"
              upperBound="-1" eType="ecore:EClass DAM_Library.ecore#//Complex_DA_Types/Complex_Data_Types/DaFailure"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="hazard" ordered="false"
              upperBound="-1" eType="ecore:EClass DAM_Library.ecore#//Complex_DA_Types/Complex_Data_Types/DaHazard"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="recovery" ordered="false"
              upperBound="-1" eType="ecore:EClass DAM_Library.ecore#//Complex_DA_Types/Complex_Data_Types/DaRec"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="confLevel" ordered="false"
              upperBound="-1" eType="ecore:EDataType DAM_Library.ecore#//Basic_DA_Types/Basic_Data_Types/DaLevel"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="integLevel" ordered="false"
              upperBound="-1" eType="ecore:EDataType DAM_Library.ecore#//Basic_DA_Types/Basic_Data_Types/DaLevel"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="DaStep" eSuperTypes="#//DAM_UML_Extensions/System/Core/DaService ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_AnalysisModel/GQAM/GaStep">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false"
              lowerBound="1" eType="ecore:EEnum DAM_Library.ecore#//Basic_DA_Types/Basic_Enumeration_Types/StepKind"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="error" ordered="false"
              upperBound="-1" eType="ecore:EClass DAM_Library.ecore#//Complex_DA_Types/Complex_Data_Types/DaError"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="fault" ordered="false"
              upperBound="-1" eType="ecore:EClass DAM_Library.ecore#//Complex_DA_Types/Complex_Data_Types/DaFault"
              containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="DaResistance" eSuperTypes="#//DAM_UML_Extensions/System/Core/DaService">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="coverage" ordered="false"
              eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Percentage"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="DaRecognition" eSuperTypes="#//DAM_UML_Extensions/System/Core/DaService"/>
        <eClassifiers xsi:type="ecore:EClass" name="DaRecovery" eSuperTypes="#//DAM_UML_Extensions/System/Core/DaService"/>
        <eClassifiers xsi:type="ecore:EClass" name="DaServiceMode">
          <eStructuralFeatures xsi:type="ecore:EReference" name="service" upperBound="-1"
              eType="#//DAM_UML_Extensions/System/Core/DaService"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="qos" upperBound="-1"
              eType="ecore:EClass DAM_Library.ecore#//Complex_DA_Types/Complex_Data_Types/DaSurvivability"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="prob" ordered="false"
              eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Percentage"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_State" ordered="false"
              lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//State"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="DaServiceRequest">
          <eOperations name="requestSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
            <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
              <details key="documentation" value="self.serviceProb->size() = self.request->size()"/>
            </eAnnotations>
            <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
              <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
                <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
              </eAnnotations>
            </eParameters>
            <eParameters name="context">
              <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
                <details key="documentation" value="The cache of context-specific information."/>
              </eAnnotations>
              <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
                <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
                <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
              </eGenericType>
            </eParameters>
          </eOperations>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessProb" ordered="false"
              upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceProb" upperBound="-1"
              eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="request" unique="false"
              upperBound="-1" eType="#//DAM_UML_Extensions/System/Core/DaService"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Classifier"
              ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Lifeline" ordered="false"
              lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Lifeline"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Interaction"
              ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Interaction"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_InstanceSpecification"
              ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="DaConnector">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="coupling" ordered="false"
              upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="errorProp" ordered="false"
              upperBound="-1" eType="ecore:EClass DAM_Library.ecore#//Complex_DA_Types/Complex_Data_Types/DaErrorPropagation"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="failure" ordered="false"
              upperBound="-1" eType="ecore:EClass DAM_Library.ecore#//Complex_DA_Types/Complex_Data_Types/DaFailure"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="hazard" ordered="false"
              upperBound="-1" eType="ecore:EClass DAM_Library.ecore#//Complex_DA_Types/Complex_Data_Types/DaHazard"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_InvocationAction"
              ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//InvocationAction"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Extend" ordered="false"
              lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Extend"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Include" ordered="false"
              lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Include"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Message" ordered="false"
              lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Message"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Connector" ordered="false"
              lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Connector"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Dependency"
              ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Dependency"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Association"
              ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="DaChange">
          <eStructuralFeatures xsi:type="ecore:EReference" name="threats" ordered="false"
              eType="#//DAM_UML_Extensions/System/Core/DaStep"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="recognition" ordered="false"
              eType="#//DAM_UML_Extensions/System/Core/DaRecognition"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="recovery" ordered="false"
              eType="#//DAM_UML_Extensions/System/Core/DaRecovery"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="resistance" ordered="false"
              eType="#//DAM_UML_Extensions/System/Core/DaResistance"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Transition"
              ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Transition"/>
        </eClassifiers>
      </eSubpackages>
      <eSubpackages name="Redundancy" nsURI="http://com.masdes.dam/profiles/Redundancy/1.0"
          nsPrefix="Redundancy">
        <eClassifiers xsi:type="ecore:EClass" name="DaController" eSuperTypes="#//DAM_UML_Extensions/System/Core/DaComponent"/>
        <eClassifiers xsi:type="ecore:EClass" name="DaVariant" eSuperTypes="#//DAM_UML_Extensions/System/Core/DaComponent"/>
        <eClassifiers xsi:type="ecore:EClass" name="DaAdjudicator" eSuperTypes="#//DAM_UML_Extensions/System/Core/DaComponent">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorDetecCoverage"
              ordered="false" upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Percentage"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="DaRedundantStructure">
          <eOperations name="packageSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
            <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
              <details key="documentation" value="self.ownedElements->size() > 2&#xA;and&#xA;self.ownedElements->size() > self.FTlevel"/>
            </eAnnotations>
            <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
              <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
                <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
              </eAnnotations>
            </eParameters>
            <eParameters name="context">
              <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
                <details key="documentation" value="The cache of context-specific information."/>
              </eAnnotations>
              <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
                <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
                <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
              </eGenericType>
            </eParameters>
          </eOperations>
          <eStructuralFeatures xsi:type="ecore:EReference" name="commonModeFailure"
              ordered="false" upperBound="-1" eType="ecore:EClass DAM_Library.ecore#//Complex_DA_Types/Complex_Data_Types/DaFailure"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="commonModeHazard"
              ordered="false" upperBound="-1" eType="ecore:EClass DAM_Library.ecore#//Complex_DA_Types/Complex_Data_Types/DaHazard"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="FTlevel" ordered="false"
              lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
              defaultValueLiteral="0"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
              lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="DaSpare" eSuperTypes="#//DAM_UML_Extensions/System/Core/DaComponent">
          <eOperations name="excludeSelfElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
            <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
              <details key="documentation" value="self.substituteFor.excludes(self.oclAsType(DaComponent))"/>
            </eAnnotations>
            <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
              <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
                <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
              </eAnnotations>
            </eParameters>
            <eParameters name="context">
              <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
                <details key="documentation" value="The cache of context-specific information."/>
              </eAnnotations>
              <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
                <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
                <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
              </eGenericType>
            </eParameters>
          </eOperations>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="dormancyFactor" ordered="false"
              upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="substituteFor" ordered="false"
              unique="false" upperBound="-1" eType="#//DAM_UML_Extensions/System/Core/DaComponent"/>
        </eClassifiers>
      </eSubpackages>
    </eSubpackages>
    <eSubpackages name="Threats" nsURI="http://com.masdes.dam/profiles/Threats/1.0"
        nsPrefix="Threats">
      <eClassifiers xsi:type="ecore:EClass" name="DaErrorPropRelation">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="propagationExpr" ordered="false"
            lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="errorProp" upperBound="-1"
            eType="ecore:EClass DAM_Library.ecore#//Complex_DA_Types/Complex_Data_Types/DaErrorPropagation"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Constraint" ordered="false"
            lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Constraint"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DaFaultGenerator" eSuperTypes="../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_AnalysisModel/GQAM/GaWorkloadGenerator">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfFaults" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Integer"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="fault" ordered="false"
            eType="ecore:EClass DAM_Library.ecore#//Complex_DA_Types/Complex_Data_Types/DaFault"
            containment="true"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="Maintenance" nsURI="http://com.masdes.dam/profiles/Maintenance/1.0"
        nsPrefix="Maintenance">
      <eClassifiers xsi:type="ecore:EClass" name="DaReplacementStep" eSuperTypes="#//DAM_UML_Extensions/System/Core/DaStep">
        <eOperations name="replaceSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="self.replace.size() = self.with.size()"/>
          </eAnnotations>
          <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
            <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
              <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
            </eAnnotations>
          </eParameters>
          <eParameters name="context">
            <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
              <details key="documentation" value="The cache of context-specific information."/>
            </eAnnotations>
            <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
              <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
              <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
            </eGenericType>
          </eParameters>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="kindRepS" ordered="false"
            lowerBound="1" eType="ecore:EEnum DAM_Library.ecore#//Basic_DA_Types/Basic_Enumeration_Types/StepKind"
            defaultValueLiteral="replacement"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="replace" upperBound="-1"
            eType="#//DAM_UML_Extensions/System/Core/DaComponent"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="with" upperBound="-1"
            eType="#//DAM_UML_Extensions/System/Redundancy/DaSpare"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DaReallocationStep" eSuperTypes="#//DAM_UML_Extensions/System/Core/DaStep">
        <eOperations name="mapSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="self.map.size() = self.to.size()"/>
          </eAnnotations>
          <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
            <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
              <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
            </eAnnotations>
          </eParameters>
          <eParameters name="context">
            <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
              <details key="documentation" value="The cache of context-specific information."/>
            </eAnnotations>
            <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
              <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
              <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
            </eGenericType>
          </eParameters>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="kindRealS" ordered="false"
            lowerBound="1" eType="ecore:EEnum DAM_Library.ecore#//Basic_DA_Types/Basic_Enumeration_Types/StepKind"
            defaultValueLiteral="reallocation"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="map" upperBound="-1"
            eType="#//DAM_UML_Extensions/System/Core/DaComponent"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="to" unique="false"
            upperBound="-1" eType="#//DAM_UML_Extensions/System/Redundancy/DaSpare"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DaActivationStep" eSuperTypes="#//DAM_UML_Extensions/System/Core/DaStep">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="kindActS" ordered="false"
            lowerBound="1" eType="ecore:EEnum DAM_Library.ecore#//Basic_DA_Types/Basic_Enumeration_Types/StepKind"
            defaultValueLiteral="activation"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="prio" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Integer"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="preemption" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Boolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="failCause" ordered="false"
            upperBound="-1" eType="#//DAM_UML_Extensions/System/Core/DaStep"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="agents" ordered="false"
            upperBound="-1" eType="#//DAM_UML_Extensions/Maintenance/DaAgentGroup"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DaAgentGroup">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="skill" ordered="false"
            lowerBound="1" eType="ecore:EEnum DAM_Library.ecore#//Basic_DA_Types/Basic_Enumeration_Types/SkillType"
            defaultValueLiteral="hwTechnician"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="correctness" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="agentNumber" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Integer"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Classifier" ordered="false"
            lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
