<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DAM_Library" nsURI="http://com.masdes.dam/libraries/DAM/DAM_Library/1.0"
    nsPrefix="DAM_Library">
  <eSubpackages name="Complex_DA_Types" nsURI="http://com.masdes.dam/libraries/DAM/Complex_DA_Types/1.0"
      nsPrefix="Complex_DA_Types">
    <eSubpackages name="Complex_Data_Types" nsURI="http://com.masdes.dam/libraries/DAM/Complex_Data_Types/1.0"
        nsPrefix="Complex_Data_Types">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="Data_Types"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EClass" name="DaError">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="latency" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="cause" ordered="false"
            upperBound="-1" eType="#//Complex_DA_Types/Complex_Data_Types/DaFault"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="effectF" ordered="false"
            upperBound="-1" eType="#//Complex_DA_Types/Complex_Data_Types/DaFailure"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="effectH" ordered="false"
            upperBound="-1" eType="#//Complex_DA_Types/Complex_Data_Types/DaHazard"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DaFault">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="occurrenceRate" ordered="false"
            upperBound="-1" eType="#//Basic_DA_Types/Basic_Data_Types/DaFrequency"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="latency" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="occurrenceProb" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="occurrenceDist" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_CommonType"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistency" ordered="false"
            eType="#//Basic_DA_Types/Basic_Enumeration_Types/Persistency"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="effectE" ordered="false"
            upperBound="-1" eType="#//Complex_DA_Types/Complex_Data_Types/DaError"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="effectF" ordered="false"
            upperBound="-1" eType="#//Complex_DA_Types/Complex_Data_Types/DaFailure"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="effectH" ordered="false"
            upperBound="-1" eType="#//Complex_DA_Types/Complex_Data_Types/DaHazard"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="phaseCreation" ordered="false"
            upperBound="-1" eType="#//Basic_DA_Types/Basic_Enumeration_Types/PhaseCreation"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="sysBoundaries" ordered="false"
            upperBound="-1" eType="#//Basic_DA_Types/Basic_Enumeration_Types/SysBoundaries"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="phenomCause" ordered="false"
            upperBound="-1" eType="#//Basic_DA_Types/Basic_Enumeration_Types/PhenomCause"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="dimension" ordered="false"
            upperBound="-1" eType="#//Basic_DA_Types/Basic_Enumeration_Types/Origin"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="objective" ordered="false"
            upperBound="-1" eType="#//Basic_DA_Types/Basic_Enumeration_Types/Objective"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="intent" ordered="false"
            upperBound="-1" eType="#//Basic_DA_Types/Basic_Enumeration_Types/Intent"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="capability" ordered="false"
            upperBound="-1" eType="#//Basic_DA_Types/Basic_Enumeration_Types/Capability"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DaFailure">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="occurrenceRate" ordered="false"
            upperBound="-1" eType="#//Basic_DA_Types/Basic_Data_Types/DaFrequency"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="MTTF" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="MTBF" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="occurrenceProb" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="occurrenceDist" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_CommonType"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" ordered="false"
            eType="#//Basic_DA_Types/Basic_Enumeration_Types/Domain"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="consistency" ordered="false"
            eType="#//Basic_DA_Types/Basic_Enumeration_Types/Consistency"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="consequence" ordered="false"
            upperBound="-1" eType="#//Basic_DA_Types/Basic_Data_Types/DaCriticalLevel"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="risk" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost" ordered="false"
            upperBound="-1" eType="#//Basic_DA_Types/Basic_Data_Types/DaCurrency"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="causeF" ordered="false"
            upperBound="-1" eType="#//Complex_DA_Types/Complex_Data_Types/DaFault"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="causeE" ordered="false"
            upperBound="-1" eType="#//Complex_DA_Types/Complex_Data_Types/DaError"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="detectability" ordered="false"
            eType="#//Basic_DA_Types/Basic_Enumeration_Types/Detectabillity"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DaHazard">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="origin" ordered="false"
            eType="#//Basic_DA_Types/Basic_Enumeration_Types/FactorOrigin"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" ordered="false"
            upperBound="-1" eType="#//Basic_DA_Types/Basic_Data_Types/DaCriticalLevel"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="occurrenceProb" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="likelihood" ordered="false"
            upperBound="-1" eType="#//Basic_DA_Types/Basic_Data_Types/DaLikelihood"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="latency" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="accidentLikelihood"
            ordered="false" upperBound="-1" eType="#//Basic_DA_Types/Basic_Data_Types/DaLikelihood"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="risk" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost" ordered="false"
            upperBound="-1" eType="#//Basic_DA_Types/Basic_Data_Types/DaCurrency"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="guideword" ordered="false"
            eType="#//Basic_DA_Types/Basic_Enumeration_Types/Guideword"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="accident" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="causeF" ordered="false"
            upperBound="-1" eType="#//Complex_DA_Types/Complex_Data_Types/DaFault"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="causeE" ordered="false"
            upperBound="-1" eType="#//Complex_DA_Types/Complex_Data_Types/DaError"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DaErrorPropagation">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="from" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="to" ordered="false"
            eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="cause" ordered="false"
            eType="#//Complex_DA_Types/Complex_Data_Types/DaFailure" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="effect" ordered="false"
            eType="#//Complex_DA_Types/Complex_Data_Types/DaError" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DaRec">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="rate" ordered="false"
            upperBound="-1" eType="#//Basic_DA_Types/Basic_Data_Types/DaFrequency"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="distribution" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_CommonType"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="coverageFactor" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DaRepair">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="rate" ordered="false"
            upperBound="-1" eType="#//Basic_DA_Types/Basic_Data_Types/DaFrequency"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="MTTR" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="distribution" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_CommonType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DaSurvivability">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="metric" ordered="false"
            lowerBound="1" eType="#//Basic_DA_Types/Basic_Enumeration_Types/MetricName"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_CommonType"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="Basic_DA_Types" nsURI="http://com.masdes.dam/libraries/DAM/Basic_DA_Types/1.0"
      nsPrefix="Basic_DA_Types">
    <eSubpackages name="Basic_Data_Types" nsURI="http://com.masdes.dam/libraries/DAM/Basic_Data_Types/1.0"
        nsPrefix="Basic_Data_Types">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="Data_Types"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EDataType" name="DaLikelihood" instanceClassName="java.lang.String"/>
      <eClassifiers xsi:type="ecore:EDataType" name="DaLevel" instanceClassName="java.lang.String"/>
      <eClassifiers xsi:type="ecore:EDataType" name="DaCriticalLevel" instanceClassName="java.lang.String"/>
      <eClassifiers xsi:type="ecore:EDataType" name="DaCurrency" instanceClassName="java.lang.String"/>
      <eClassifiers xsi:type="ecore:EDataType" name="DaFrequency" instanceClassName="java.lang.String"/>
    </eSubpackages>
    <eSubpackages name="Basic_Enumeration_Types" nsURI="http://com.masdes.dam/libraries/DAM/Basic_Enumeration_Types/1.0"
        nsPrefix="Basic_Enumeration_Types">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="Enumeration_Types"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EEnum" name="Persistency">
        <eLiterals name="transient"/>
        <eLiterals name="permanent" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="Domain">
        <eLiterals name="content"/>
        <eLiterals name="earlyTiming" value="1"/>
        <eLiterals name="lateTiming" value="2"/>
        <eLiterals name="halt" value="3"/>
        <eLiterals name="erratic" value="4"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="Consistency">
        <eLiterals name="consistent"/>
        <eLiterals name="inconsistent" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="Detectabillity">
        <eLiterals name="signaled"/>
        <eLiterals name="unsignaled" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="FactorOrigin">
        <eLiterals name="endogenous"/>
        <eLiterals name="exogenous" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="Guideword">
        <eLiterals name="value"/>
        <eLiterals name="omission" value="1"/>
        <eLiterals name="commission" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="PhaseCreation">
        <eLiterals name="development"/>
        <eLiterals name="operational" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="SysBoundaries">
        <eLiterals name="internal"/>
        <eLiterals name="external" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="PhenomCause">
        <eLiterals name="natural"/>
        <eLiterals name="humanMade" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="Objective">
        <eLiterals name="malicious"/>
        <eLiterals name="nonMalicious" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="Intent">
        <eLiterals name="deliberate"/>
        <eLiterals name="nonDeliberate" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="Capability">
        <eLiterals name="accidental"/>
        <eLiterals name="incompetence" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="MetricName">
        <eLiterals name="ssAvail"/>
        <eLiterals name="instAvail" value="1"/>
        <eLiterals name="unreliability" value="2"/>
        <eLiterals name="reliability" value="3"/>
        <eLiterals name="missionTime" value="4"/>
        <eLiterals name="availLevel" value="5"/>
        <eLiterals name="reliabLevel" value="6"/>
        <eLiterals name="safetyLevel" value="7"/>
        <eLiterals name="respT" value="8"/>
        <eLiterals name="confLevel" value="9"/>
        <eLiterals name="integLevel" value="10"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="DaFrequencyUnitKind">
        <eLiterals name="ft_s"/>
        <eLiterals name="ft_ms" value="1"/>
        <eLiterals name="ft_min" value="2"/>
        <eLiterals name="ft_hr" value="3"/>
        <eLiterals name="ft_day" value="4"/>
        <eLiterals name="ft_month" value="5"/>
        <eLiterals name="ft_yr" value="6"/>
        <eLiterals name="fail_s" value="7"/>
        <eLiterals name="fail_ms" value="8"/>
        <eLiterals name="fail_min" value="9"/>
        <eLiterals name="fail_hr" value="10"/>
        <eLiterals name="fail_day" value="11"/>
        <eLiterals name="fail_month" value="12"/>
        <eLiterals name="fail_yr" value="13"/>
        <eLiterals name="repair_s" value="14"/>
        <eLiterals name="repair_ms" value="15"/>
        <eLiterals name="repair_min" value="16"/>
        <eLiterals name="repair_hr" value="17"/>
        <eLiterals name="repair_day" value="18"/>
        <eLiterals name="repair_month" value="19"/>
        <eLiterals name="repair_yr" value="20"/>
        <eLiterals name="rec_s" value="21"/>
        <eLiterals name="rec_ms" value="22"/>
        <eLiterals name="rec_min" value="23"/>
        <eLiterals name="rec_hr" value="24"/>
        <eLiterals name="rec_day" value="25"/>
        <eLiterals name="rec_month" value="26"/>
        <eLiterals name="rec_yr" value="27"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="CriticalLevel">
        <eLiterals name="minor"/>
        <eLiterals name="marginal" value="1"/>
        <eLiterals name="major" value="2"/>
        <eLiterals name="catastrophic" value="3"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="Level">
        <eLiterals name="veryHigh"/>
        <eLiterals name="high" value="1"/>
        <eLiterals name="medium" value="2"/>
        <eLiterals name="low" value="3"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="Likelihood">
        <eLiterals name="frequent"/>
        <eLiterals name="moderate" value="1"/>
        <eLiterals name="occasional" value="2"/>
        <eLiterals name="remote" value="3"/>
        <eLiterals name="unlikely" value="4"/>
        <eLiterals name="impossible" value="5"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="StepKind">
        <eLiterals name="error"/>
        <eLiterals name="failure" value="1"/>
        <eLiterals name="hazard" value="2"/>
        <eLiterals name="reallocation" value="3"/>
        <eLiterals name="replacement" value="4"/>
        <eLiterals name="activation" value="5"/>
        <eLiterals name="fault" value="6"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="SkillType">
        <eLiterals name="hwTechnician"/>
        <eLiterals name="swTechnician" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="DaCurrKind">
        <eLiterals name="euro"/>
        <eLiterals name="dollar" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="Origin">
        <eLiterals name="hw"/>
        <eLiterals name="sw" value="1"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
